export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const ADD_NEW_ITEM = "ADD_NEW_ITEM";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
